CREATE TABLE ut_decklist (
    card_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    card_name TEXT NOT NULL,
    image_url TEXT NOT NULL,
    multiverseid INTEGER NOT NULL,
    deck_id INTEGER REFERENCES ut_decks(deck_id) ON DELETE CASCADE
);